#!/bin/bash
#This Program is comparing 5 numbers and gives you what number is bigger!


i=1 #frist number for loops

max=0  #value to compare loops via var1

#For loop

for i in {1..5}
do
        read -p "Enter $i numeber: " var1
        if [ $var1 -gt $max ]

        then
                max=$var1
        fi
                i=$i+1
done
#result is new 'max' value

echo "The max number is : $max"

#End of Script

