#!/bin/bash
#This programs compares any number from 10 

#Read user input and write it on var1 
read -p "enter a number: " var1

#Start if - else Loops 
if [ $var1 -eq 10 ]
then
        echo "This number is even"
elif [ $var1 -lt 10 ]
then
        echo "this number is less than"
else
        echo "this number is more than"
fi

echo "Good lock!'

#End of Scripts
