#!/bin/bash
#This programs compares any number from 10 

#Reads user input and write it on var1 
read -p "Enter a number: " var1

#Start if - else Loops 
if [ $var1 -eq 10 ]
then
        echo "This number is even"
elif [ $var1 -lt 10 ]
then
        echo "This number is less than 10"
else
        echo "This number is more than 10"
fi

echo "Good lock!"

#End of Scripts
